### PR TITLE
Create Cross Account VPC Peers using AWS Lambda and CloudFormation.

### PR DESCRIPTION
**Pull request by ruhlem**
Issue
Customer need to automate the process to create VPC Peers between VPCs owned by different accounts.

Short Description
VPC Peering facilitates network traffic between VPCs. By default, CloudFormation does not support creating VPC peering connections between VPCs owned by different accounts.  

Resolution
Using AWS Lambda and CloudFormation Custom Resources we can go around this limitation, allowing the creation of the VPC Peers from within a CloudFormation Stack.

### CODE REVIEW

**Comment by LRomandine** [comment]
Sent internal email requesting
- Create readme.md
- Internal Amazon Legal ticket #

**Comment by LRomandine** [comment]
Can you remove the license file?  The whole repo already has a license file, no need to duplicate it.

Also, I think we can move this into the /aws/solutions/ folder since you are aws and it's a solution.  I feel like the /community/solutions/ folder is for non-Amazon contributions.

**Comment by LRomandine** [comment]
Can you also include in the readme some simple instructions for use?  They don't have to be precise, just some simple stuff like...

1. run cloudformation A in account A
2. run cloudformation B in account B
3. Invoke Lambda from account B

**Comment by ruhlem** [comment]
Changes done as requested.

**Pull request merged**
