### PR TITLE
Add DataPipeline Definition based on DataPipeline Documentation

### PR DESCRIPTION
**Pull request by nishantcasey**
This template describes how to translate the definition found in the DataPipeline definition found in the documentation here: 

http://docs.aws.amazon.com/datapipeline/latest/DeveloperGuide/dp-object-emrconfiguration.html

This includes a way to provide multiple array values in the same 'StringValue' by using a combination of double and single quotes.

### CODE REVIEW

**Comment by LRomandine** [comment]
Thank you for your contribution!

A few notes are below, once both are complete I can merge.

Please move and rename the CloudFormation template to
community/services/DataPipeline/multiple-StringValue/multiple-StringValue.json

Please create a readme.md here with a detailed how-to
community/services/DataPipeline/multiple-StringValue/readme.md

**Comment by LRomandine** [comment]
Loos like it's still under the /aws/ directory and not the /community/ directory.

**Comment by nishantcasey** [comment]
So - as I am AWS and the template is born from customer issues with finding a solution to this in documentation (and seeing as ellitoyam specifically asked me to add this here..)
Should it not be in aws/services?

**Comment by LRomandine** [comment]
Ah, sorry about that.  I tried to find you in the internal tool but I guess I didn't try hard enough.  Merging now.

**Pull request merged**
